/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ascenseur;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class IGAscenseur extends javax.swing.JFrame implements Runnable {
    
    /**
     * Creates new form IGAscenseur
     */
    Ascenseur ascenseur;
    public IGAscenseur() {
        
        this.ascenseur=new Ascenseur(2,5,this);
        Thread mytread=new Thread(ascenseur);
        mytread.start();
        initComponents();
        this.setImage("C:\\ascf.png");
        
    }
    @Override
    public void run(){
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelText = new javax.swing.JLabel();
        ouvrebtn = new javax.swing.JButton();
        LabelImage = new javax.swing.JLabel();
        LabelStatus = new javax.swing.JLabel();
        LabelEtage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelText.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelText.setText("Etat d'Ascenseur");

        ouvrebtn.setBackground(new java.awt.Color(153, 153, 255));
        ouvrebtn.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        ouvrebtn.setText("Ouvrir");
        ouvrebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ouvrebtnActionPerformed(evt);
            }
        });

        LabelStatus.setBackground(new java.awt.Color(255, 255, 255));
        LabelStatus.setForeground(new java.awt.Color(0, 204, 0));
        LabelStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelStatus.setText("monte :");

        LabelEtage.setForeground(new java.awt.Color(255, 0, 51));
        LabelEtage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelEtage.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LabelImage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LabelText, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ouvrebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelEtage)
                        .addGap(117, 117, 117)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(LabelText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ouvrebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelStatus)
                    .addComponent(LabelEtage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ouvrebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ouvrebtnActionPerformed
        // TODO add your handling code here:
        String nom;
        int etageAct;
        int etageAriv;
        nom=JOptionPane.showInputDialog(this, "Veuillez enter le nom ", "nom",JOptionPane.PLAIN_MESSAGE);
        etageAct=Integer.parseInt(JOptionPane.showInputDialog(this, "etage ou vous etes", "etage",JOptionPane.PLAIN_MESSAGE)); 
        etageAriv=Integer.parseInt(JOptionPane.showInputDialog(this, "etage que vous vouliez", "etage",JOptionPane.PLAIN_MESSAGE));
        
        Personne personne=new Personne(nom,etageAriv,etageAct,this.ascenseur,this);
        Thread mythread2=new Thread(personne);
        mythread2.start();
    }//GEN-LAST:event_ouvrebtnActionPerformed
     public void setImage(String chemin){
    ImageIcon icon= new ImageIcon(chemin);
    Image img=icon.getImage();
    Image imgScale=img.getScaledInstance(100, LabelImage.getHeight(), Image.SCALE_SMOOTH);
    ImageIcon scaleIcon=new ImageIcon(imgScale);
    LabelImage.setIcon(icon);
    
    
    }
    public void setText(String title){
    LabelText.setText(title);
    
    }
    
    public void setstatus(String title){
    LabelStatus.setText(title);
    }
    public void setetage(String e){
    LabelEtage.setText(e);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IGAscenseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IGAscenseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IGAscenseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IGAscenseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IGAscenseur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelEtage;
    private javax.swing.JLabel LabelImage;
    private javax.swing.JLabel LabelStatus;
    private javax.swing.JLabel LabelText;
    private javax.swing.JButton ouvrebtn;
    // End of variables declaration//GEN-END:variables
}
