/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package deuxAscenseur;

import ascenseur.Ascenseur;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class IGAscenseur extends javax.swing.JFrame {

    /**
     * Creates new form IGAscenseur
     */
    Ascenceur ascenseurd;
    Ascenceur ascenseurg;
    
    public IGAscenseur() {
        this.ascenseurd=new Ascenceur(2,5,this);
        Thread mytread1=new Thread(ascenseurd);
        mytread1.start();
        this.ascenseurg=new Ascenceur(3,5,this);
        Thread mytreadg=new Thread(ascenseurg);
        mytreadg.start();
        initComponents();
        this.setImage("C:\\ascf.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelImage = new javax.swing.JLabel();
        LabelText = new javax.swing.JLabel();
        entrebtn = new javax.swing.JButton();
        LabelStatus = new javax.swing.JLabel();
        LabelEtage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        LabelText.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelText.setText("AscenseurStatus");

        entrebtn.setBackground(new java.awt.Color(153, 153, 255));
        entrebtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        entrebtn.setText("entrer");
        entrebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrebtnActionPerformed(evt);
            }
        });

        LabelStatus.setForeground(new java.awt.Color(51, 204, 0));
        LabelStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelStatus.setText("monte :");

        LabelEtage.setForeground(new java.awt.Color(255, 51, 51));
        LabelEtage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelEtage.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelText, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(LabelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelEtage))
                            .addComponent(entrebtn))))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LabelText, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entrebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LabelStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelEtage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entrebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrebtnActionPerformed
        // TODO add your handling code here:
         String nom;
        int etageAct;
        int etageAriv;
        String asc;
        nom=JOptionPane.showInputDialog(this, "Veuillez enter le nom ", "nom",JOptionPane.PLAIN_MESSAGE);
        etageAct=Integer.parseInt(JOptionPane.showInputDialog(this, "etage ou vous etes", "etage",JOptionPane.PLAIN_MESSAGE)); 
        etageAriv=Integer.parseInt(JOptionPane.showInputDialog(this, "etage que vous vouliez", "etage",JOptionPane.PLAIN_MESSAGE));
        asc=JOptionPane.showInputDialog(this, "Veuillez choisir l'ascenseur:gauche|droite ", "asc",JOptionPane.PLAIN_MESSAGE);
        System.out.println(asc);
        if(asc.equalsIgnoreCase("droite"))
        {Personne personne=new Personne(nom,etageAriv,etageAct,this.ascenseurd,this,"droite");
        Thread mythread2=new Thread(personne);
        mythread2.start();}
        else if(asc.equalsIgnoreCase("gauche")){
            Personne personne=new Personne(nom,etageAriv,etageAct,this.ascenseurg,this,"gauche");
            Thread mythread2=new Thread(personne);
            mythread2.start();
        
        }
        else{System.out.println("valeur invalid");}
    }//GEN-LAST:event_entrebtnActionPerformed
    public void setImage(String chemin){
    ImageIcon icon= new ImageIcon(chemin);
    Image img=icon.getImage();
    Image imgScale=img.getScaledInstance(100, LabelImage.getHeight(), Image.SCALE_SMOOTH);
    ImageIcon scaleIcon=new ImageIcon(imgScale);
    LabelImage.setIcon(icon);
    
    
    }
    public void setText(String title){
    LabelText.setText(title);
    
    }
    public void setstatus(String title){
    LabelStatus.setText(title);
    }
    
     public void setetage(String e){
    LabelEtage.setText(e);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IGAscenseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IGAscenseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IGAscenseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IGAscenseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IGAscenseur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelEtage;
    private javax.swing.JLabel LabelImage;
    private javax.swing.JLabel LabelStatus;
    private javax.swing.JLabel LabelText;
    private javax.swing.JButton entrebtn;
    // End of variables declaration//GEN-END:variables
}
